### ISSUE TITLE
Remove `Documenter` and  `Revise` from dependencies

### ISSUE THREAD

**Issue by fingolfin** [singular-gpispace/GromovWitten#70]
Please remove both `Documenter` and `Revise` from `Project.toml`. Neither belongs in there.

I think we were there before, and they keep getting added due to the way you invoke `julia`. Please do *not* use
```
julia --project=.
```
or if you do, then at least make sure not to add packages there.

**Comment by fingolfin** [comment]
That will also stop those CompatHelper PRs from being reopened automatically.... That is, you will fix the cause of that instead of constantly battling a symptom

**Comment by blociss** [comment]
> Please remove both `Documenter` and `Revise` from `Project.toml`. Neither belongs in there.
> 
> I think we were there before, and they keep getting added due to the way you invoke `julia`. Please do _not_ use
> 
> ```
> julia --project=.
> ```
> 
> or if you do, then at least make sure not to add packages there.

If I remove Documenter, then I can't verify my  ```jldoctest  block anymore.

**Comment by blociss** [comment]
> I would recommend #71
> 
> The instructions in your README are really dangerous: suggesting to do `julia --project` is not a good idea, and are the source of this issue and the weird Pkg hackery you are doing in `docs/make.jl`. I'll make a PR to suggest a cleanup


Should I use this instead? 
`import Pkg; Pkg.activate(".")`
`import Pkg; Pkg.instantiate()`
`using GromovWitten`
